### ISSUE TITLE
Google OAuth not working 

### ISSUE THREAD

**Issue by titidutarn** [didalgolab/chatgpt-intellij-plugin#19] opened 2024-04-11 09:47 UTC
Couldn’t sign you in
This browser or app may not be secure. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en-US)
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.

**Comment by didalgolab** [comment] 2024-05-05 21:43
It cannot be fixed. Please read this comment: https://github.com/didalgolab/chatgpt-intellij-plugin/issues/5#issuecomment-1692263268

**Comment by didalgolab** [comment] 2024-05-05 21:44
Duplicate of #5

**Closed by didalgolab** 2024-05-05 21:44 UTC
